### ISSUE TITLE
Need a way to get string from the screen

### ISSUE THREAD

**Issue by vshymanskyy** [AmuletTechnologies/AmuletLCD#4]
This is currently not implemented in the library.
@AmuletTechnologies @AmuletDeters

**Comment by AmuletTechnologies** [comment]
I'll see if I can get this done before the holiday break. Something like:

`uint8_t  requestString(uint16_t start, uint8_t * destination_buffer, uint16_t buffer_length)`

I don't think strings should be done the same as the other data types, mainly because of the memory requirements of dedicating several KB just to the InternalRAM string buffer, like the AmuletOS does.

**Comment by AmuletDeters** [comment]
Ok, try it out now. I did some preliminary testing and it seems to work fine but I didn't try to break it yet.

**Comment by vshymanskyy** [comment]
It works! Thank you, and Merry Christmas!
